### ISSUE TITLE
Package dependencies get lost in all package

### ISSUE THREAD

**Issue by cnagel** [wcm-io-devops/conga-aem-plugin#59]
By default, the conga aem plugin adds dependencies to every sub package in the all-package to preserve an installation order.
When a package contains a dependency to another package, the **dependency gets overwritten**.

This is reproducible with the wcm.io AEM archetype. Just add a package dependency from _conf-content_ to _sample-content_.
The _conf-content package_ in the all-package has a dependency to _adobe/consulting:acs-aem-commons-all:6.0.10_ in the end.

With configuration `<autoDependenciesMode>OFF</autoDependenciesMode>` the **dependency gets completely removed** and the entry in the vault properties is empty: `<entry key="dependencies"></entry>`.

This causes problems when using the AECU cloud distribution 6.4. This contains two packages for the Groovy Console. Without dependencies, _aem-groovy-console-ui.apps_ overwrites the content of _aem-groovy-console-ui.apps.aem_ and the console is not usable anymore.

A first fix should prevent the deletion of package dependencies when configuration has `<autoDependenciesMode>OFF</autoDependenciesMode>`.

**Comment by cnagel** [comment]
I've debugged the plugin with the wcm.io archetype example.
The dependency gets lost in the [AllPackageBuilder.java](https://github.com/wcm-io-devops/conga-aem-plugin/blob/8fb45bb8b59dc1be5d21f47ca4c330702dd8bda9/tooling/conga-aem-maven-plugin/src/main/java/io/wcm/devops/conga/plugins/aem/maven/allpackage/AllPackageBuilder.java#L695).

Maybe we have to extend the if clause around it to `if (existingDeps != null && dependencyFile != null) {`.
This should fix the `<autoDependenciesMode>OFF</autoDependenciesMode>` configuration and would not touch the default auto dependencies mode.

**Comment by stefanseifert** [comment]
> By default, the conga aem plugin adds dependencies to every sub package in the all-package to preserve an installation order. When a package contains a dependency to another package, the dependency gets overwritten.

this is by design. when you use a `AutoDependenciesMode` other then `OFF` all existing references to packages that are managed by CONGA are removed, and replaced with the order in the conga role.

> With configuration <autoDependenciesMode>OFF</autoDependenciesMode> the dependency gets completely removed and the entry in the vault properties is empty: <entry key="dependencies"></entry>.

this looks like a bug, probably a regression introduced during fine-tuning of the dependency management. those dependencies should be preserved, but may have to be rewritten if the references package name has changed (e.g. because of adding the runmode prefix).
